# Generated by Django 4.1.3 on 2022-11-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('real_estate_type', models.CharField(choices=[('room', 'Room'), ('apartment', 'Apartment'), ('house', 'House'), ('storage', 'Storage'), ('garage', 'Garage'), ('commercial', 'Commercial')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Advertisment',
        ),
    ]
