# Generated by Django 4.1.3 on 2022-11-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0002_advertisement_delete_advertisment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='area',
            field=models.FloatField(default=1.0, verbose_name='Area, m^2'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.CharField(default='Kyiv', max_length=50, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price, uah'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='real_estate_type',
            field=models.CharField(choices=[('room', 'Room'), ('apartment', 'Apartment'), ('house', 'House'), ('storage', 'Storage'), ('garage', 'Garage'), ('commercial', 'Commercial')], max_length=10, verbose_name='Real Estate Type'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Advertisement Title'),
        ),
    ]
