# Generated by Django 4.1.3 on 2022-11-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0003_advertisement_area_advertisement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='contact_number',
            field=models.CharField(default='+380', max_length=13, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='area',
            field=models.FloatField(default=1.0, verbose_name='Area (sq.m.)'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price (UAH)'),
        ),
    ]
