# Generated by Django 4.1.3 on 2022-11-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0004_advertisement_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='contact_number',
            field=models.CharField(default='+380', max_length=14, verbose_name='Contact Number'),
        ),
    ]
