# Generated by Django 4.1.3 on 2022-11-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0005_advertisement_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='photo',
        ),
    ]
